spring:
  datasource:
    url: jdbc:postgresql://db.mwjutuydtmgrioljrnbk.supabase.co:5432/postgres
    username: postgres
    password: K6bUw1xu69wty5jq
  jpa:
    hibernate:
      ddl-auto: update

auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168
